// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-pE0pfsTtChgs09WGAfwH67siCz0oMx4',
    appId: '1:737480520969:web:9066810ea6c82cd01c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    authDomain: 'sanctionnateur-5b794.firebaseapp.com',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
    measurementId: 'G-MBFR4FX3XN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-QTBJTIsCXtr0pP_cn-NdMTavFdod88',
    appId: '1:737480520969:android:f0e2e1e5c8cb31a61c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKUCJlOM2G2lUdzAsqMGHZgfgopb4z67Y',
    appId: '1:737480520969:ios:f1b89496fedf5bd31c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
    iosClientId: '737480520969-06t9jgcbsg80egnhhgocb85vgk2d8mtu.apps.googleusercontent.com',
    iosBundleId: 'org.starland.sanctionnateur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKUCJlOM2G2lUdzAsqMGHZgfgopb4z67Y',
    appId: '1:737480520969:ios:f1b89496fedf5bd31c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
    iosClientId: '737480520969-06t9jgcbsg80egnhhgocb85vgk2d8mtu.apps.googleusercontent.com',
    iosBundleId: 'org.starland.sanctionnateur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-pE0pfsTtChgs09WGAfwH67siCz0oMx4',
    appId: '1:737480520969:web:1be82e189182a8ef1c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    authDomain: 'sanctionnateur-5b794.firebaseapp.com',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
    measurementId: 'G-X1FGK9BH0Q',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC-pE0pfsTtChgs09WGAfwH67siCz0oMx4',
    appId: '1:737480520969:web:171bd63c8e180f8c1c4fd8',
    messagingSenderId: '737480520969',
    projectId: 'sanctionnateur-5b794',
    authDomain: 'sanctionnateur-5b794.firebaseapp.com',
    storageBucket: 'sanctionnateur-5b794.appspot.com',
    measurementId: 'G-QBW4RL3S2T',
  );
}
